[package]
name = "chainreversi-rust"
version = "0.1.0"
authors = ["Stephen Cross <scross@scross.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
sfml = "0.14.0"
